"""Constants for the Anova Precision Oven integration."""

DOMAIN = "anova_precision_oven"

CONF_TOKEN = "token"

ACCESSORIES_APO = "APO"

WS_ENDPOINT = "wss://devices.anovaculinary.io"
WS_TIMEOUT = 30
WS_RECONNECT_DELAY = 30
WS_MAX_MESSAGE_SIZE = 10 * 1024 * 1024

OVEN_TYPE_V1 = "oven_v1"
OVEN_TYPE_V2 = "oven_v2"

CMD_APO_START = "CMD_APO_START"
CMD_APO_STOP = "CMD_APO_STOP"
CMD_APO_SET_LAMP = "CMD_APO_SET_LAMP"

EVENT_APO_WIFI_LIST = "EVENT_APO_WIFI_LIST"
EVENT_APO_STATE = "EVENT_APO_STATE"

TEMP_MIN_CELSIUS = 25
TEMP_MAX_CELSIUS = 250

DEFAULT_TEMPERATURE_CELSIUS = 175
DEFAULT_FAN_SPEED = 100
DEFAULT_HUMIDITY = 0
